// https://github.com/pages-themes/minimal/blob/master/README.md
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme #

title: [My Favorite Songs]
description: [Here are my favorite songs.]
